name: Delete Preview Database
description: "Cleans up preview databases created for preview branches"
on:
  pull_request:
    types: [closed]

inputs:
  github-token:
    description: "GitHub token"
    required: true
  dotenv-me:
    description: "DOTENV_ME secret"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
